name: Build and Test
permissions: read-all
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3
      
      - name: cache bazel build artifacts
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # pin@v3.3.1
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelrc', 'WORKSPACE', 'bazel/import_llvm.bzl') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      
      - name: "Run `bazel build`"
        run: |
          bazel build //...
      
      - name: "Run `bazel test`"
        run: |
          bazel test //...